export const Action = {
  START_SESSION: 'START_SESSION',
  CONNECT_WATCH: 'CONNECT_WATCH',
  RECEIVE_DATA_WATCH: 'RECEIVE_DATA_WATCH',
  GET_WATCH_DATA: 'GET_WATCH_DATA',
  SAVE_SESSION_LOCAL: 'SAVE_SESSION_LOCAL',
  DELETE_SESSIONS: 'DELETE_SESSIONS',
  GET_SESSION_BY_ID: 'GET_SESSION_BY_ID',
  GET_SESSION_INFO: 'GET_SESSION_INFO',
  EXECUTE_QUERY: 'EXECUTE_QUERY',
  GET_VIZUALIZATIONS: 'GET_VIZUALIZATIONS',
  SAVE_SESSION_LOCAL_TABLET: 'SAVE_SESSION_LOCAL_TABLET',
  EXPORT_SESSION_TO_DISTANT_SERVER: 'EXPORT_SESSION_TO_DISTANT_SERVER',
  STOP_SESSION: 'STOP_SESSION',
};

export const Status = {
  IDLE: 3,
  STOP: 0,
  START: 1,
};

export const ERROR_CODE = {
  FAIL_CONNECT_TO_SERVER: -1,
};
